### ISSUE TITLE
Can't use library dependencies

### ISSUE THREAD

**Issue by Sciss** [JetBrains/sbt-idea-example#7]
The readme is very vague about how to add libraries that my plugin will depend on. I moved them in the Project Settings > Artifacts > libraries from 'available elements' to '<output root>', which gives me something like this:

    <root id="root" />

```scala
<component name="ArtifactManager">
  <artifact name="libraries">
    <output-path>$PROJECT_DIR$/target/artifacts/libraries</output-path>
    <root id="root">
      <element id="library" level="project" name="sbt: com.itextpdf:itextpdf:5.5.13:jar" />
      <element id="library" level="project" name="sbt: com.jhlabs:filters:2.0.235:jar" />
      <element id="library" level="project" name="sbt: com.mortennobel:java-image-scaling:0.8.6:jar" />
      ...
  </artifact>
</component>
```

And I see those jars now being copied to `target/artifacts/libraries`. But when when running the IDEA run configuration and using my plugin, I get a `NoClassDefFoundError` as soon as I need one of the libraries.

What am I doing wrong? Would be great to clarify the process in the README. Thank you.

**Comment by Sciss** [comment]
Strangely, the library is in the package jar, like

    $ jar tf target/artifacts/plugin/lib/idea-plugin.jar | grep fileutil
    fileutil_2.12.jar

So I must be doing something wrong if I still get `NoClassDefFoundError` ?

**Comment by ShaneDelmore** [comment]
I'm hitting the same issue.  The plugin dependency docs don't reference SBT at all. Examples would be helpful here.  https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_dependencies.html

**Comment by Sciss** [comment]
I think the problem is that you cannot have nested jars, so the example is basically wrong. I now have them like this:

https://github.com/Sciss/Mellite-IDEA/blob/9c2d31c3bd5923b6d3886ce808de3c80f13bea88/.idea/artifacts/libraries.xml

But there is no automatic update mechanism; for example, if I update a library, I have remove the old version, put the new version, check all dependencies. I think there should be an automatic way to do that.

**Comment by mutcianm** [comment]
This template has been rewritten from scratch after being deprecated for a while.
It is now used by the `New Project | Scala | IntelliJ Platform Plugin` wizard.
Closing as obsolete.
